### ISSUE TITLE
Add php 8.1 support

### ISSUE THREAD

**Issue by foresight-developers** [TopOnePercent/baum#25]
Currently experience this error:

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php:637
Stack trace:
#0 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php(20): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(578): include('...')
#2 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php(31): Composer\Autoload\ClassLoader->loadClass()
#4 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php(332): Illuminate\Foundation\Bootstrap\SetRequestForConsole->bootstrap()
#5 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php(223): Orchestra\Testbench\TestCase->resolveApplicationBootstrappers()
#6 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase.php(73): Orchestra\Testbench\TestCase->createApplication()
#7 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/Testing.php(79): Orchestra\Testbench\TestCase->refreshApplication()
#8 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase.php(41): Orchestra\Testbench\TestCase->setUpTheTestEnvironment()
#9 /home/runner/work/baum/baum/tests/Baseline/UnitAbstract.php(14): Orchestra\Testbench\TestCase->setUp()
#10 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCase.php(1147): Baum\Tests\Baseline\UnitAbstract->setUp()
#11 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#12 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult->run()
#13 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestCase->run()
#14 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run()
#15 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run()
#[16](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:17) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite->run()
#[17](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:18) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#[18](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:19) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#[19](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:20) /home/runner/work/baum/baum/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#[20](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:21) /home/runner/work/baum/baum/vendor/bin/phpunit(123): include('...')
#[21](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:22) {main} in /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 20
..
In Request.php line 20:
                                                                               
  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of   
  Illuminate\Http\Request::offsetExists($offset) should either be compatible   
  with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWi  
  llChange] attribute should be used to temporarily suppress the notice in /h  
  ome/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Requ  
  est.php:637                                                                  
  Stack trace:                                                                 
  #0 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http  
  /Request.php(20): Illuminate\Foundation\Bootstrap\HandleExceptions->handleE  
  rror()                                                                       
  #1 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(578): includ  
  e('...')                                                                     
  #2 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(432): Compos  
  er\Autoload\ClassLoader::Composer\Autoload\{closure}()                       
  #3 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Foun  
  dation/Bootstrap/SetRequestForConsole.php(31): Composer\Autoload\ClassLoade  
  r->loadClass()                                                               
  #4 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /CreatesApplication.php(332): Illuminate\Foundation\Bootstrap\SetRequestFor  
  Console->bootstrap()                                                         
  #5 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /CreatesApplication.php([22](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:23)3): Orchestra\Testbench\TestCase->resolveApplicat  
  ionBootstrappers()                                                           
  #6 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase  
  .php(73): Orchestra\Testbench\TestCase->createApplication()                  
  #7 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /Testing.php(79): Orchestra\Testbench\TestCase->refreshApplication()         
  #8 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase  
  .php(41): Orchestra\Testbench\TestCase->setUpTheTestEnvironment()            
  #9 /home/runner/work/baum/baum/tests/Baseline/UnitAbstract.php(14): Orchest  
  ra\Testbench\TestCase->setUp()                                               
  #10 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCa  
  se.php(1147): Baum\Tests\Baseline\UnitAbstract->setUp()                      
  #11 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestRe  
  sult.php(728): PHPUnit\Framework\TestCase->runBare()                         
  #12 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCa  
  se.php(904): PHPUnit\Framework\TestResult->run()                             
  #13 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestCase->run()                              
  #14 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestSuite->run()                             
  #15 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestSuite->run()                             
  #16 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/TestRunne  
  r.php(653): PHPUnit\Framework\TestSuite->run()                               
  #17 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.p  
  hp(144): PHPUnit\TextUI\TestRunner->run()                                    
  #18 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.p  
  hp(97): PHPUnit\TextUI\Command->run()                                        
  #19 /home/runner/work/baum/baum/vendor/phpunit/phpunit/phpunit(98): PHPUnit  
  \TextUI\Command::main()                                                      
  #20 /home/runner/work/baum/baum/vendor/bin/phpunit(1[23](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:24)): include('...')      
  #21 {main}

**Comment by bkintanar** [comment]
@foresight-developers do you have any updates on this issue, do you still require help solving it?

**Comment by foresight-developers** [comment]
@bkintanar our development team is currently working on some internal projects and will allocate time to this prior to php 8's support being fully dropped later this year. 

That being said we would appreciate any work put towards this in the mean time.

**Comment by foresight-developers** [comment]
@bkintanar I just approved and ran the github actions checks and they have failed, let me know if you need any help with that and I'll see if we can get some development time allocated internally.

**Comment by bkintanar** [comment]
@foresight-developers I've tested it locally with 7.4, 8.0, and 8.1 and I've updated my PR. Can you approve again please?

**Comment by bkintanar** [comment]
@foresight-developers test is still failing even though it's just a warning for P8.1

**Comment by foresight-developers** [comment]
@bkintanar we can update the github actions test to ignore that warning I think, we will look into that shortly
