### ISSUE TITLE
README needs a little fix

### ISSUE THREAD

**Issue by lucasborges24** [TopOnePercent/baum#33]
In the image below, it's described that running `make:baum {model_name}` will generate both a **Model** and a **Migration**:

<img width="849" alt="image" src="https://github.com/TopOnePercent/baum/assets/54027010/158fb8ad-20fc-4172-8298-4a588442c6cb">

However, in the latest version, _3.1.0_, only the Model is generated, as you can see below:

![image](https://github.com/TopOnePercent/baum/assets/54027010/4c53522c-c140-4aec-8f56-fc2edd4dd4a9)

Due to the great generosity of the person who created the package, there's an example of a migration to create the table right below in the documentation. Nevertheless, just as it caused confusion for me, the statement about the creation of both files might confuse other users!

Thank you very much!

**Comment by BilalAslim** [comment]
@lucasborges24 would you like "make:baum {model_name}" to generate both a Model and a Migration? do you think that is the most practical usage? 

I think it would be best to keep them separate and update the readme as you have suggested.

Thanks for catching this!

**Comment by lucasborges24** [comment]
I personally believe the current way is preferable! Updating the Readme was indeed my suggestion :)

Additionally, I was going through the documentation yesterday while implementing some code, and I stumbled upon another discrepancy in the readme:

In the section where you detail the ancestors/descendant methods, there's a slight mix-up with the sibling method's description:

![image](https://github.com/TopOnePercent/baum/assets/54027010/71d39fd4-ba12-4786-9460-3e75ea1aff46)

I believe the more accurate descriptions would be:

`getSiblingsAndSelf()`: Retrieve all **siblings of the node**, including the node itself.
`getSiblings()`: Return all **siblings of the node**, excluding the node itself.

By the way, I'm genuinely excited about this package! While working with it, I realized there was a particular method I couldn't find . I'd love to take the initiative and implement it in a PR. I believe it could be a valuable addition to the package.

Hope this helps and thank you for the continuous work on this package!

**Comment by BilalAslim** [comment]
@lucasborges24 I agree with you I prefer the current way. I will double check it works like that then get the wording updated. As for the other wording changes I agree as the wording you proposed fits the verbage of the other functions better and its clearer. 

That being said feel free to open an issue for a new method and make a fork to work on it. 

I will most likely get these wording changes done in the next 2 weeks.
